export const SHOW_CHART = 'SHOW_CHART'
export const HIDE_CHART = 'HIDE_CHART'

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
